Add `JS_StrictEq()`, `JS_SameValue()`, and `JS_SameValueZero()`
bellard/quickjs pull request #264
Opened 2024-04-02 12:44 UTC by kasperisager

2024-04-27 00:33 UTC, xeioex commented
@chqrlie 

This patch seems reasonable to me too, and I need functionality like this as well.
Do you plan to accept patches likes this which expose low-level API? What is the general policy for accepting new patches?

2024-05-08 21:18 UTC, xeioex commented
@chqrlie A kind reminder.

2024-05-08 21:26 UTC, chqrlie requested changes

2024-05-08 21:26 UTC, chqrlie commented on quickjs.c
> +
For consistency, this API should also take 2 `JSValueConst` operands.

Suggestion:
```
BOOL JS_StrictEq(JSContext *ctx, JSValueConst op1, JSValueConst op2)
{
    return js_strict_eq(ctx,  JS_DupValue(ctx, op1), JS_DupValue(ctx, op2));
}
```

2024-05-09 11:06 UTC, chqrlie approved these changes

2024-05-09 11:07 UTC, merged