Add JS_NewTypedArray
bellard/quickjs pull request #272
Opened 2024-04-05 06:29 UTC by xeioex

2024-05-05 16:39 UTC, chqrlie requested changes

2024-05-05 16:39 UTC, chqrlie commented on quickjs.c
> +}
You should add a range check and either return `JS_UNDEFINED` or throw an exception.  The check could be performed in `js_typed_array_constructor` instead.

2024-05-08 20:59 UTC, chqrlie requested changes

2024-05-08 20:59 UTC, chqrlie commented on quickjs.c
> +
Sorry I should have been more explicit: The exception should be a Range Error.

2024-05-08 21:08 UTC, chqrlie approved these changes

2024-05-08 21:17 UTC, merged

2024-05-09 12:29 UTC, chqrlie commented
After further thinking, I am not sure about the arguments to C API `JS_NewTypedArray`: It should probably take a `size_t length` and a `const void *` to optionally initialize the array contents. `argc` + `argv` is for JavaScript methods.

What is your use case?

2024-05-09 17:24 UTC, xeioex commented
@chqrlie 

I will prepare the updated API and PR.